name: NodeJS API CI

on:
    push:
        branches-ignore:
            - master
            - gh-pages

jobs:
    api-tests:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: api

        strategy:
            matrix:
                node-version: [ 16.x ]

        steps:
            -   uses: actions/checkout@v2

            -   name: Run API tests with NodeJS ${{ matrix.node-version }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node-version }}
                    cache: "npm"
                    cache-dependency-path: api/package-lock.json

            -   name: Install dependencies
                run: npm ci

            -   name: Run API tests
                env:
                    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                run: npm run test

    api-e2e:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./api

        strategy:
            matrix:
                node-version: [ 16.x ]

        steps:
            -   uses: actions/checkout@v2

            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node-version }}
                    cache: "npm"
                    cache-dependency-path: api/package-lock.json

            -   name: Install dependencies
                run: npm ci

            -   name: Run e2e API tests
                env:
                    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                run: npm run test:e2e

    api-lint:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./api

        strategy:
            matrix:
                node-version: [ 16.x ]

        steps:
            -   uses: actions/checkout@v2

            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node-version }}
                    cache: "npm"
                    cache-dependency-path: api/package-lock.json

            -   name: Install dependencies
                run: npm ci

            -   name: Run API linter
                run: npm run lint
