name: Node.js CI

on:
    push:
        branches-ignore:
            - master
            - gh-pages

jobs:
    tests:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./client

        strategy:
            matrix:
                node-version: [ 16.x ]

        steps:
            -   uses: actions/checkout@v2

            -   name: Run client tests with NodeJS ${{ matrix.node-version }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node-version }}
                    cache: "npm"

            -   name: Install dependencies
                run: npm ci

            -   name: Run client tests
                run: npm run test:prod

    e2e:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./client

        strategy:
            matrix:
                node-version: [ 16.x ]

        steps:
            -   uses: actions/checkout@v2

            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node-version }}
                    cache: "npm"

            -   name: Install dependencies
                run: npm ci

            -   name: Run e2e client tests
                run: npm run e2e:ci

    lint:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./client

        strategy:
            matrix:
                node-version: [ 16.x ]

        steps:
            -   uses: actions/checkout@v2

            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node-version }}
                    cache: "npm"

            -   name: Install dependencies
                run: npm ci

            -   name: Run client linter
                run: npm run lint
