name: Client deployment on GitHub pages

on:
    push:
        branches: [ master ]

jobs:
    deploy:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: client

        strategy:
            matrix:
                node-version: [ 16.x ]

        steps:
            -   uses: actions/checkout@v2

            -   name: Auto-deploy with NodeJS ${{ matrix.node-version }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node-version }}
                    cache: "npm"
                    cache-dependency-path: client/package-lock.json

            -   name: Set GitHub credentials
                run: |
                    git config --global user.email "romain-thd+github@protonmail.com"
                    git config --global user.name "RomainTHD"

            -   name: Install dependencies
                run:
                    npm ci

            -   name: Deploy to GitHub pages
                run: npm run deploy:gh-pages
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
